services:
  db:
    image: mysql:8.0.33
    container_name: mysql-3
    #    restart: always
    environment:
        MYSQL_DATABASE: your-database-name
        MYSQL_ROOT_USERNAME: your-username
        MYSQL_ROOT_PASSWORD: your-password
    volumes:
      - db:/var/lib/mysql
    ports:
      - "your-port-database"
    networks:
      - name-your-network


  app1:
    image: allisonms/blog-repository:latest
    container_name: blog
    #    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:your-port-database/your-database-name
      SPRING_DATASOURCE_USERNAME: your-database-username
      SPRING_DATASOURCE_PASSWORD: your-database-password
    depends_on:
      - db
    ports:
      - "your-port"
    networks:
      - name-your-network


networks:
  name-your-network:
    driver: bridge

volumes:
  db:
